# Configuration for the application
page_title: "IMAGINE Machines Monitor" # Title displayed on the web page

# Define host details here, mapping aliases to connection info
host_details:
  passerelle:
    hostname: passerelle.enpc.fr
    user: alexandros.benetatos@enpc.fr
    # No jump host for the jump host itself
  imagine:
    hostname: imagine.enpc.fr
    user: alexandros.benetatos@enpc.fr
    jump_host_alias: passerelle # Reference the alias of the jump host
  allier:
    hostname: allier.enpc.fr
    user: abenetatos
    jump_host_alias: passerelle # Reference the alias of the jump host

# List of hosts to monitor by alias (must match keys in host_details)
## The host alias used as a jump point to access other machines.
## Must match a key in host_details. Set to null or omit if no jump host.
jump_host: passerelle
monitored_hosts:
  - alias: imagine
    check_gpu: false # Do not check for GPUs on this host
  - alias: allier
    check_gpu: true # Explicitly check for GPUs on this host

# Refresh interval for fetching status updates in seconds
refresh_interval_no_clients_sec: 3600
refresh_interval_clients_sec: 300
